#!/bin/bash

serifCollection=(
    "素晴らしく注意力がないな、君は"
    "はっはっは、typoかね"
    "ふーむ、typoのようだね"
    "ふむ、typoじゃないかな"
)

length=${#serifCollection[@]}

index=$((RANDOM % length))
echo ${serifCollection[index]}

exit 0
